spring:
  profiles:
    active: local
  config:
    import:
      - external.yml
---
server:
  port: 10030
spring:
  config:
    activate:
      on-profile: local
  r2dbc:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_ROOT_PASSWORD}
  kafka:
    bootstrap-servers: localhost:29092,localhost:39092,localhost:49092
logging:
  level:
    org.springframework.r2dbc: DEBUG
    reactor.netty.http.client: DEBUG
