spring:
  profiles:
    active: local
---
server:
  port: 10010
spring:
  config:
    activate:
      on-profile: local
  r2dbc:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_ROOT_PASSWORD}
