spring:
  profiles:
    active: local
---
server:
  port: 10010
spring:
  config:
    activate:
      on-profile: local
  r2dbc:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_ROOT_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      database: ${REDIS_DATABASE}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  kafka:
    bootstrap-servers: localhost:29092,localhost:39092,localhost:49092
    consumer:
      group-id:
        order: order-stock-consumer
      topics:
        order-stock-rollback: order.product-stock-rollback
logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
