services:
  mysql:
    image: mysql:8.0.31
    container_name: idolu-mysql
    ports:
      - "3306:3306"
    volumes:
      - ./init-docker/mysql/volume:/var/lib/mysql
      - ./init-docker/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${TZ}
    networks:
      - idolu-dev
  redis:
    image: redis:7.0
    container_name: idolu-redis
    ports:
      - "6379:6379"
    volumes:
      - ./init-docker/redis/data:/data
      - ./init-docker/redis/conf/redis.conf:/usr/local/conf/redis.conf
    restart: always
    command: redis-server /usr/local/conf/redis.conf
    networks:
      - idolu-dev
  zookeeper1:
    image: confluentinc/cp-zookeeper:7.2.7
    hostname: zookeeper1
    container_name: zookeeper1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181 # 클라이언트(Kafka 브로커 등)이 Zookeeper 연결할 때 사용하는 포트
      ZOOKEEPER_SERVER_ID: 1 # Zookeeper 클러스터 내 고유 서버 id
      # Zookeeper 클러스터 내 고유 서버 id
      ZOOKEEPER_SERVERS: zookeeper1:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888 # 2888 port: leader노드가 follower 노드를 위해 열어 두는 port(동기화 용도) -> follower가 leader에게 연결 요청을 하기 위한 포트, 3888 port: leader 선출을 위한 election용 포트
      ZOOKEEPER_TRICK_TIME: 2000 # zookeeper가 클러스터를 구성할 때의 동기화 틱 시간 설정
      ZOOKEEPER_INIT_LIMIT: 5 # 팔로워가 리더와 연결을 시도할 수 있는 시간 제한. 타임 아웃 시간은 ZOOKEEPER_TRICK_TIME*ZOOKEEPER_INIT_LIMIT = 2000*5 = 10,000(10초)가 됨
      ZOOKEEPER_SYNC_LIMIT: 2  # 팔로워가 리더와 연결된 후, 앙상블 안에서 리더와 동기화되기 위한 최대 제한 수. 싱크 시간은 ZOOKEEPER_TRICK_TIME*ZOOKEEPER_SYNC_LIMIT = 2000*2 = 4000(4초)가 됨
    networks:
      - idolu-dev
  zookeeper2:
    image: confluentinc/cp-zookeeper:7.2.7
    hostname: zookeeper2
    container_name: zookeeper2
    ports:
      - "2182:2182"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_SERVERS: zookeeper1:2888:3888;zookeeper2:2888:3888;zookeeper2:2888:3888 # 2888 port: leader노드가 follower 노드를 위해 열어 두는 port(동기화 용도) -> follower가 leader에게 연결 요청을 하기 위한 포트, 3888 port: leader 선출을 위한 election용 포트
      ZOOKEEPER_TRICK_TIME: 2000 # zookeeper가 클러스터를 구성할 때의 동기화 틱 시간 설정
      ZOOKEEPER_INIT_LIMIT: 5 #팔로워가 리더와 연결시도를 하는 최대 횟수
      ZOOKEEPER_SYNC_LIMIT: 2  #팔로워가 리더와 연결된 후, 앙상블 안에서 리더와 동기화되기 위한 제한 수.
    networks:
      - idolu-dev
  zookeeper3:
    image: confluentinc/cp-zookeeper:7.2.7
    hostname: zookeeper3
    container_name: zookeeper3
    ports:
      - "2183:2183"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2183
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_SERVERS: zookeeper1:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888 # 2888 port: leader노드가 follower 노드를 위해 열어 두는 port(동기화 용도) -> follower가 leader에게 연결 요청을 하기 위한 포트, 3888 port: leader 선출을 위한 election용 포트
      ZOOKEEPER_TRICK_TIME: 2000 # zookeeper가 클러스터를 구성할 때의 동기화 틱 시간 설정
      ZOOKEEPER_INIT_LIMIT: 5 #팔로워가 리더와 연결시도를 하는 최대 횟수
      ZOOKEEPER_SYNC_LIMIT: 2  #팔로워가 리더와 연결된 후, 앙상블 안에서 리더와 동기화되기 위한 제한 수.
    networks:
      - idolu-dev
  kafka1:
    image: confluentinc/cp-kafka:7.2.7
    hostname: kafka1
    container_name: kafka1
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2182,zookeeper3:2183
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092,PLAINTEXT_HOST://localhost:29092  # 브로커 간 통신용,로컬 개발 환경에서 Kafka 접근 시 사용,호스트 OS에서 Docker 내부 Kafka 접근 시 사용
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT  # 각 리스너 이름에 대해 어떤 보안 프로토콜을 적용할지 설정, PLAINTEXT로 설정되어 있어 인증 없이 통신 가능 (개발용)
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    networks:
      - idolu-dev
  kafka2:
    image: confluentinc/cp-kafka:7.2.7
    hostname: kafka2
    container_name: kafka2
    ports:
      - "39092:39092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2182,zookeeper3:2183
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092,PLAINTEXT_HOST://localhost:39092 # producer, consumer에 노출할 주소
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT  # 각 리스너 이름에 대해 어떤 보안 프로토콜을 적용할지 설정, PLAINTEXT로 설정되어 있어 인증 없이 통신 가능 (개발용)
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    networks:
      - idolu-dev
  kafka3:
    image: confluentinc/cp-kafka:7.2.7
    hostname: kafka3
    container_name: kafka3
    ports:
      - "49092:49092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2182,zookeeper3:2183
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9092,PLAINTEXT_HOST://localhost:49092 # producer, consumer에 노출할 주소
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT  # 각 리스너 이름에 대해 어떤 보안 프로토콜을 적용할지 설정, PLAINTEXT로 설정되어 있어 인증 없이 통신 가능 (개발용)
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    networks:
      - idolu-dev
  kafka-ui:
    image: provectuslabs/kafka-ui
    hostname: kafka-ui
    container_name: kafka-ui
    ports:
      - "28080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper1:2181,zookeeper2:2182,zookeeper3:2183
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092,kafka2:9093,kafka3:9094
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
      - kafka1
      - kafka2
      - kafka3
    networks:
      - idolu-dev
networks:
  idolu-dev:
    driver: bridge
